### PR TITLE
Korath Raider Update: Raider Mark XLII Asset

### PR DESCRIPTION
**Pull request by Saugia**
Blend File for the Raider Mk.II.

### CODE REVIEW

**Review by Zitchas — DISMISSED** [review]
Thanks for making this!

**Comment by Saugia** [comment]
Not sure what "dismissed stale review' means

**Comment by Zitchas** [comment]
That means that someone made a review, and there's been enough changes made to the content that the review doesn't apply anymore. So, it's "stale".

**Review by Zitchas — APPROVED** [review]
Looks good, although I'm curious as to if there are any separate files for the raider thumbnail

**Comment by Saugia** [comment]
Nope, it's from the one blend file, just rendered by activating different lights and cameras

**Comment by Zitchas** [comment]
Sounds good.

**Pull request merged**
