### PR TITLE
Ship Thumbnail assets update

### PR DESCRIPTION
**Pull request by Anarchist2**
### PR Summary
Updates the ship thumbnail assets to be up to date with https://github.com/endless-sky/endless-sky/commit/47b899685d527f842b74e4b2b164e0a821327c5d. Also deletes some outdated assets.
#### Missing assets:
- [x] The Peregrine Thumbnail is still missing.

### CODE REVIEW

**Comment by Anarchist2** [comment]
So should I add back the old files?

**Comment by Amazinite** [comment]
No, that’s taken care of by git. Each file has a history that people can go back into if they want an older version.

**Comment by ravenshining** [comment]
Self-reminder to re-upload the Raider blend; it seems every time someone comes into my server wanting to edit or borrow parts from the Raider, they grab the wrong model

**Comment by Amazinite** [comment]
[Peregrine](https://discord.com/channels/251118043411775489/266345072554016768/950033606657581077).

**Pull request merged**
