### PR TITLE
Non-Ship non-outfit assets update

### PR DESCRIPTION
**Pull request by Anarchist2**
## PR Summary
Updates non-ship non-outfit assets to be up to date with https://github.com/endless-sky/endless-sky/commit/47b899685d527f842b74e4b2b164e0a821327c5d. Also deletes some outdated assets.

### Missing assets:
- [ ] The scene, doctored landscape files, planet sprite and postverta station from https://github.com/endless-sky/endless-sky/pull/4871 are missing assets.
- [ ] The plant asteroids, nebula planet and scene image from https://github.com/endless-sky/endless-sky/pull/6392.
- [ ] The non-outfit assets from https://github.com/endless-sky/endless-sky/pull/6310. Zitchas said that the files were PSDs though.
- [x] The only assets available for the pug explosions are the initial ones from https://github.com/endless-sky/endless-sky/pull/3957, as opposed to the committed ones that have rotation. Not that the pug explosions were in the assets directory in the first place. Maintainer note: The committed images could be derived from the available assets, so it's not really that important to have the exact rotation for each image.
- [x] The Subsidurial death sprite from https://github.com/endless-sky/endless-sky/pull/4785 is missing.
- [x] The scene in https://github.com/endless-sky/endless-sky/pull/5198.
- [x] The new stations from https://github.com/endless-sky/endless-sky/pull/5670. Feel free to trawl through a year's worth of messages on discord.

### MZ's stuff:
- [ ] None of the UI assets were updated to reflect the changes made in https://github.com/endless-sky/endless-sky/commit/fb62445a3968f6d736cacd9bf1408dd0546fb5b0.
- [ ] The remnant and coalition flare source files are missing.
- [ ] The files for ES's high-definition icon (the flying berserker) are missing.
- [ ] Assets for the cargo box are missing.
- [ ] Files for the hallucination rainbows are missing.

### Can ignore:
- ~~The new stars from https://github.com/endless-sky/endless-sky/pull/5828, but that PR noted that the source files were in the GBs, so maybe not.~~ Yeah, let's just not worry about 3 gig photoshop files.
- ~~The .xcf for the `sky2` landscape (Skymoot) from https://github.com/endless-sky/endless-sky/pull/3404 is missing.~~ I've reached out about it but this is several years old now and likely lost to time.
- ~~The planets from https://github.com/endless-sky/endless-sky/pull/5229.~~ Reported gone from the artist.
- ~~The new flares from https://github.com/endless-sky/endless-sky/pull/5474~~ No changes were made to assets.
- ~~Maybe the new images from https://github.com/endless-sky/endless-sky/pull/6450 and https://github.com/endless-sky/endless-sky/pull/6462? I know that they're just crops, but the assets repo already has a huge chuck of .xcfs for landscapes.~~ Don't really need the uncropped versions.
- ~~Not sure what the policy is on sound assets. The only asset in it right now is Kat's red JD.~~ We'll discuss sound assets later if the need arises.

### CODE REVIEW

**Comment by Amazinite** [comment]
Edited the OP to scratch out stuff we don't need. The Coalition engine flares change just cropped the output differently compared to what was done before; the existing assets file still has the same exact image. I'd say that landscape images don't need assets as they're almost always just cropped images; we don't really need the full original. Sound assets we can figure out later if we want to, but for now I'd say it's fine if there are new sounds that we don't have assets for.

**Comment by Anarchist2** [comment]
The Coalition flares were noticeably altered from just their alignment; see the difference in the very tip of the flare:
image

**Comment by Amazinite** [comment]
> The Coalition flares were noticeably altered from just their alignment; see the difference in the very tip of the flare:

Can confirm from Vital that the only change that was made was to shift the image.

**Comment by Amazinite** [comment]
Going to just take what we have so far and move the tracking of missing items to #1.

**Pull request merged**
